"""LSFG-VK release management: fetching, caching, metadata, and installation.

LSFG-VK is a Vulkan frame-generation layer (from PancakeTAS/lsfg-vk).
Installation places files in standard XDG locations:
  - liblsfg-vk.so        → ~/.local/lib/
  - VkLayer_*.json        → ~/.local/share/vulkan/implicit_layer.d/
  - ~/lsfg               (generated wrapper script)

Usage in Steam: ~/lsfg %command%
Prerequisite: Lossless Scaling must be installed via Steam.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tarfile
import tempfile
import threading
import time
import zipfile
from pathlib import Path
from typing import Any
from urllib.request import Request, urlopen

import decky  # type: ignore[import-untyped]  # pylint: disable=import-error

from .http_client import curl_download, curl_json
from .plugin_utils import extract_archive_safely
from .proton_ge import finalize_extracted_compat_tool
from .steam_paths import compat_tools_cache_dir

LSFG_VK_REPO_API = (
    "https://api.github.com/repos/PancakeTAS/lsfg-vk/releases?per_page=10"
)
LSFG_VK_CACHE_TTL_SECONDS = 6 * 60 * 60
LSFG_VK_LATEST_SLOT_NAME = "lsfg-vk-latest"
# Launch wrapper script placed in the user's home dir, matching the
# decky-lsfg-vk convention: `~/lsfg %command%`
LSFG_WRAPPER_SCRIPT = Path.home() / "lsfg"
LSFG_LIB_DIR = Path.home() / ".local" / "lib"
LSFG_VULKAN_LAYER_DIR = Path.home() / ".local" / "share" / "vulkan" / "implicit_layer.d"


# --- Install directory ---

def lsfg_vk_install_dir() -> Path:
    """Return (and create) the versioned LSFG-VK install base directory."""
    d = Path.home() / ".local" / "share" / "lsfg"
    d.mkdir(parents=True, exist_ok=True)
    return d


def get_binary_path() -> Path | None:
    """Return the ~/lsfg wrapper script path if it exists, else None."""
    if LSFG_WRAPPER_SCRIPT.exists():
        return LSFG_WRAPPER_SCRIPT
    return None


def is_binary_available() -> bool:
    """Return True if the ~/lsfg wrapper script is present."""
    return LSFG_WRAPPER_SCRIPT.exists()


def _write_wrapper_script(install_dest: Path) -> bool:
    """Write (or overwrite) the ~/lsfg launch wrapper script.

    The script mirrors the pattern used by decky-lsfg-vk: it exports
    LSFG_* environment variables and execs the game command.  We generate
    a minimal version that just sets the library path and execs.
    """
    # Find the .so in the install directory
    so_path: Path | None = None
    for candidate in sorted(install_dest.rglob("*.so")):
        if "lsfg" in candidate.name.lower():
            so_path = candidate
            break

    if so_path is None:
        # No .so found yet; still write a minimal wrapper so the binary
        # presence check passes - the user can reinstall to fix.
        decky.logger.warning("lsfg-vk: no .so found in install dir, writing minimal wrapper")

    # Place the .so in ~/.local/lib/ and the Vulkan layer manifest if present.
    LSFG_LIB_DIR.mkdir(parents=True, exist_ok=True)
    LSFG_VULKAN_LAYER_DIR.mkdir(parents=True, exist_ok=True)

    if so_path and so_path.exists():
        dest_so = LSFG_LIB_DIR / so_path.name
        try:
            shutil.copy2(so_path, dest_so)
            decky.logger.info(f"lsfg-vk: installed {so_path.name} to {LSFG_LIB_DIR}")
        except OSError as e:
            decky.logger.warning(f"lsfg-vk: failed to copy .so: {e}")
        # Vulkan layer JSON manifest
        for json_file in install_dest.rglob("*.json"):
            if "vklayer" in json_file.name.lower() or "implicit" in json_file.name.lower() or "lsfg" in json_file.name.lower():
                dest_json = LSFG_VULKAN_LAYER_DIR / json_file.name
                try:
                    shutil.copy2(json_file, dest_json)
                    decky.logger.info(f"lsfg-vk: installed Vulkan layer manifest {json_file.name}")
                except OSError as e:
                    decky.logger.warning(f"lsfg-vk: failed to copy layer JSON: {e}")

    script_content = f"""\
#!/usr/bin/env bash
# Generated by Proton Pulse - LSFG-VK wrapper
# Usage: ~/lsfg %command%
export LD_LIBRARY_PATH="{LSFG_LIB_DIR}:$LD_LIBRARY_PATH"
exec "$@"
"""
    try:
        LSFG_WRAPPER_SCRIPT.write_text(script_content, encoding="utf-8")
        LSFG_WRAPPER_SCRIPT.chmod(0o755)
        decky.logger.info(f"lsfg-vk: wrote wrapper script to {LSFG_WRAPPER_SCRIPT}")
        return True
    except OSError as e:
        decky.logger.warning(f"lsfg-vk: failed to write wrapper script: {e}")
        return False


def _remove_installed_files() -> None:
    """Remove the ~/lsfg script and installed .so / Vulkan layer files."""
    for p in (LSFG_WRAPPER_SCRIPT,):
        try:
            if p.exists():
                p.unlink()
                decky.logger.info(f"lsfg-vk: removed {p}")
        except OSError as e:
            decky.logger.warning(f"lsfg-vk: failed to remove {p}: {e}")


# --- Release simplification ---

def simplify_lsfg_release(release: dict[str, Any]) -> dict[str, Any] | None:
    """Boil a raw GitHub release payload down to what the frontend needs."""
    if release.get("draft") or release.get("prerelease"):
        return None
    tag = release.get("tag_name") or ""
    if not tag:
        return None

    assets: list[dict[str, Any]] = release.get("assets", [])
    asset = next(
        (
            a for a in assets
            if (
                any(
                    a.get("name", "").endswith(ext)
                    for ext in (".tar.gz", ".tar.xz", ".zip", ".tar.bz2")
                )
                and not a.get("name", "").endswith(".sig")
                and "source" not in a.get("name", "").lower()
            )
        ),
        None,
    )
    if not asset:
        return None

    return {
        "tag_name": tag,
        "name": release.get("name") or tag,
        "published_at": release.get("published_at"),
        "prerelease": release.get("prerelease", False),
        "asset_name": asset.get("name"),
        "download_url": asset.get("browser_download_url"),
        "asset_size": asset.get("size"),
    }


# --- Metadata persistence ---

def _latest_metadata_path() -> Path:
    return compat_tools_cache_dir() / "lsfg-vk-latest.json"


def write_latest_metadata(tag_name: str, directory_name: str) -> None:
    path = _latest_metadata_path()
    payload = {
        "tag_name": tag_name,
        "directory_name": directory_name,
        "updated_at": int(time.time()),
    }
    path.write_text(json.dumps(payload), encoding="utf-8")


def clear_latest_metadata(directory_name: str | None = None) -> None:
    path = _latest_metadata_path()
    if not path.exists():
        return
    if directory_name is None:
        path.unlink(missing_ok=True)
        return
    try:
        payload: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        decky.logger.debug(f"Clearing LSFG-VK-Latest metadata: {e}")
        path.unlink(missing_ok=True)
        return
    if payload.get("directory_name") == directory_name:
        path.unlink(missing_ok=True)


def read_latest_metadata() -> dict[str, Any] | None:
    path = _latest_metadata_path()
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[return-value]
    except (json.JSONDecodeError, OSError):
        return None


# --- Installed version discovery ---

def list_installed_lsfg_vk(
    latest_meta: dict[str, Any] | None,
) -> list[dict[str, Any]]:
    """Scan the LSFG-VK install directory and return installed versions."""
    install_dir = lsfg_vk_install_dir()
    if not install_dir.exists():
        return []

    latest_tag = latest_meta.get("tag_name") if latest_meta else None
    result: list[dict[str, Any]] = []

    for entry in install_dir.iterdir():
        if not entry.is_dir():
            continue
        dir_name = entry.name
        is_latest_slot = dir_name == LSFG_VK_LATEST_SLOT_NAME

        if is_latest_slot:
            managed_slot: str | None = "latest"
            tag = latest_tag
        elif dir_name.startswith("lsfg-vk-"):
            managed_slot = "versioned"
            tag = dir_name[len("lsfg-vk-"):]
        else:
            managed_slot = None
            tag = None

        result.append({
            "directory_name": dir_name,
            "tag_name": tag,
            "path": str(entry),
            "managed_slot": managed_slot,
            "latest_tag": latest_tag if is_latest_slot else None,
        })

    return sorted(
        result,
        key=lambda t: (t.get("managed_slot") != "latest", t.get("directory_name") or ""),
    )


# --- Install-status tracking (thread-safe) ---

def make_initial_status() -> dict[str, Any]:
    return {
        "state": "idle",
        "tag_name": None,
        "message": None,
        "stage": None,
        "downloaded_bytes": None,
        "total_bytes": None,
        "progress_fraction": None,
        "started_at": None,
        "finished_at": None,
        "install_as_latest": False,
    }


def set_install_status(  # pylint: disable=too-many-arguments,too-many-locals
    status: dict[str, Any],
    lock: threading.Lock,
    *,
    state: str,
    tag_name: str | None,
    message: str | None,
    install_as_latest: bool,
    stage: str | None = None,
    downloaded_bytes: int | None = None,
    total_bytes: int | None = None,
    progress_fraction: float | None = None,
    started_at: int | None = None,
    finished_at: int | None = None,
) -> None:
    running = state == "running"
    with lock:
        cur_started = status.get("started_at")
        cur_stage = status.get("stage")
        cur_dl = status.get("downloaded_bytes")
        cur_total = status.get("total_bytes")
        cur_frac = status.get("progress_fraction")
        status.clear()
        status.update({
            "state": state,
            "tag_name": tag_name,
            "message": message,
            "stage": stage if stage is not None else (cur_stage if running else None),
            "downloaded_bytes": downloaded_bytes if downloaded_bytes is not None else (cur_dl if running else None),
            "total_bytes": total_bytes if total_bytes is not None else (cur_total if running else None),
            "progress_fraction": progress_fraction if progress_fraction is not None else (cur_frac if running else None),
            "started_at": started_at if started_at is not None else (cur_started if running else None),
            "finished_at": finished_at,
            "install_as_latest": install_as_latest,
        })


def get_install_status(
    status: dict[str, Any], lock: threading.Lock
) -> dict[str, Any]:
    with lock:
        return dict(status)


# --- Release fetching & caching ---

def _cache_path() -> Path:
    return compat_tools_cache_dir() / "lsfg-vk-releases-cache.json"


def fetch_releases() -> list[dict[str, Any]]:
    """Fetch LSFG-VK releases from GitHub with a 6 h disk cache."""
    cache = _cache_path()
    now = int(time.time())
    if cache.exists():
        try:
            cached = json.loads(cache.read_text())
            if now - int(cached.get("fetched_at", 0)) < LSFG_VK_CACHE_TTL_SECONDS:
                return cached.get("releases", [])  # type: ignore[no-any-return]
        except (json.JSONDecodeError, OSError, ValueError) as err:
            decky.logger.warning(f"Failed to read LSFG-VK cache: {err}")

    try:
        raw = curl_json(
            LSFG_VK_REPO_API,
            headers=["Accept: application/vnd.github+json", "User-Agent: decky-proton-pulse"],
            timeout=25,
        )
        releases = raw if isinstance(raw, list) else []
    except (subprocess.SubprocessError, OSError, json.JSONDecodeError) as err:
        decky.logger.warning(
            f"curl fetch for LSFG-VK releases failed, trying Python fallback: {err}"
        )
        request = Request(
            LSFG_VK_REPO_API,
            headers={
                "Accept": "application/vnd.github+json",
                "User-Agent": "decky-proton-pulse",
            },
        )
        with urlopen(request, timeout=20) as response:
            releases = json.loads(response.read().decode("utf-8"))  # type: ignore[assignment]

    simplified: list[dict[str, Any]] = [
        item for item in (simplify_lsfg_release(r) for r in releases) if item
    ]
    cache.write_text(
        json.dumps({"fetched_at": now, "releases": simplified}),
        encoding="utf-8",
    )
    return simplified


def get_releases_sync(force_refresh: bool = False) -> list[dict[str, Any]]:
    """Fetch releases, optionally busting cache. Falls back to stale cache on error."""
    cache = _cache_path()
    if force_refresh and cache.exists():
        cache.unlink()
    try:
        return fetch_releases()
    except (OSError, subprocess.SubprocessError, json.JSONDecodeError, ValueError) as err:
        decky.logger.error(f"Failed to fetch LSFG-VK releases: {err}")
        if cache.exists():
            try:
                return json.loads(cache.read_text(encoding="utf-8")).get("releases", [])  # type: ignore[no-any-return]
            except (json.JSONDecodeError, OSError):
                pass
        return []


# --- Synchronous install pipeline (runs on background thread) ---

def install_sync(  # pylint: disable=too-many-arguments,too-many-positional-arguments,too-many-locals,too-many-return-statements
    version: str | None,
    install_as_latest: bool,
    force_reinstall: bool,
    status: dict[str, Any],
    lock: threading.Lock,
    cancel_flag: threading.Event,
    process_ref: list[subprocess.Popen[str] | None],
) -> dict[str, Any]:
    """Download, extract, and install an LSFG-VK release."""

    def _set(**kw: Any) -> None:
        set_install_status(status, lock, **kw)

    def _cancel() -> bool:
        return cancel_flag.is_set()

    def _set_process(p: subprocess.Popen[str] | None) -> None:
        with lock:
            process_ref[0] = p

    releases = get_releases_sync(False)
    release: dict[str, Any] | None = None

    if version:
        release = next((r for r in releases if r.get("tag_name") == version), None)
        if not release:
            return {
                "success": False,
                "message": f"Could not find LSFG-VK release for {version}.",
                "release": None,
            }
    else:
        release = releases[0] if releases else None

    if not release:
        return {
            "success": False,
            "message": "No LSFG-VK release is available right now.",
            "release": None,
        }

    tag = release.get("tag_name") or ""
    decky.logger.info(
        f"Starting LSFG-VK install | version={tag} install_as_latest={install_as_latest}"
    )

    latest_meta = read_latest_metadata()
    installed = list_installed_lsfg_vk(latest_meta)
    install_dir = lsfg_vk_install_dir()

    dest_name = LSFG_VK_LATEST_SLOT_NAME if install_as_latest else f"lsfg-vk-{tag}"

    if not force_reinstall:
        if install_as_latest:
            existing_latest = next(
                (v for v in installed if v.get("managed_slot") == "latest"), None
            )
            if existing_latest and existing_latest.get("tag_name") == tag:
                return {
                    "success": True,
                    "already_installed": True,
                    "message": f"{LSFG_VK_LATEST_SLOT_NAME} already points to {tag}.",
                    "release": release,
                }
        else:
            if any(v.get("tag_name") == tag and v.get("managed_slot") != "latest" for v in installed):
                return {
                    "success": True,
                    "already_installed": True,
                    "message": f"LSFG-VK {tag} is already installed.",
                    "release": release,
                }

    download_url = release.get("download_url")
    if not download_url:
        return {
            "success": False,
            "message": f"LSFG-VK {tag} has no downloadable archive.",
            "release": release,
        }

    asset_size = release.get("asset_size")
    asset_name = release.get("asset_name") or f"lsfg-vk-{tag}.tar.gz"

    with tempfile.TemporaryDirectory(prefix="proton-pulse-lsfg-install-") as tmp:
        archive_path = Path(tmp) / asset_name
        try:
            _download_release(
                tag, download_url, archive_path, asset_size, install_as_latest,
                _set, _cancel, _set_process,
            )

            extract_dir = Path(tmp) / "extract"
            extract_dir.mkdir(parents=True, exist_ok=True)
            if _cancel():
                return _cancelled(tag, release)

            dl_bytes = archive_path.stat().st_size if archive_path.exists() else None
            _set(
                state="running", tag_name=tag,
                message=f"Extracting LSFG-VK {tag}...",
                install_as_latest=install_as_latest,
                stage="extracting",
                downloaded_bytes=dl_bytes, total_bytes=asset_size,
                progress_fraction=1.0 if asset_size else None,
            )
            extract_archive_safely(archive_path, extract_dir)
            if _cancel():
                return _cancelled(tag, release)

            _set(
                state="running", tag_name=tag,
                message=f"Finalizing LSFG-VK {tag}...",
                install_as_latest=install_as_latest,
                stage="finalizing",
                downloaded_bytes=dl_bytes, total_bytes=asset_size,
                progress_fraction=1.0,
            )
            result = finalize_extracted_compat_tool(
                tag, extract_dir, install_dir,
                destination_name=dest_name,
                replace_existing=install_as_latest or force_reinstall,
            )
            if result.get("success"):
                if install_as_latest:
                    write_latest_metadata(tag, LSFG_VK_LATEST_SLOT_NAME)
                _write_wrapper_script(install_dir / dest_name)
            result["release"] = release
            return result

        except (OSError, subprocess.SubprocessError, tarfile.TarError, zipfile.BadZipFile, ValueError) as err:
            decky.logger.error(f"Failed to install LSFG-VK {tag}: {err}")
            return {
                "success": False,
                "message": f"LSFG-VK install failed for {tag}: {err}",
                "release": release,
            }


def _download_release(  # pylint: disable=too-many-arguments,too-many-positional-arguments
    tag: str,
    download_url: str,
    archive_path: Path,
    asset_size: int | None,
    install_as_latest: bool,
    _set: Any,
    _cancel: Any,
    _set_process: Any,
) -> None:
    try:
        _set(
            state="running", tag_name=tag,
            message=f"Downloading LSFG-VK {tag}...",
            install_as_latest=install_as_latest,
            stage="downloading", downloaded_bytes=0,
            total_bytes=asset_size,
            progress_fraction=0.0 if asset_size else None,
        )

        def _dl_progress(downloaded: int, total: int | None, fraction: float | None) -> None:
            _set(
                state="running", tag_name=tag,
                message=f"Downloading LSFG-VK {tag}...",
                install_as_latest=install_as_latest,
                stage="downloading",
                downloaded_bytes=downloaded, total_bytes=total, progress_fraction=fraction,
            )

        curl_download(
            download_url, archive_path,
            timeout=900, total_bytes=asset_size,
            progress_callback=_dl_progress,
            cancel_check=_cancel,
            install_process_setter=_set_process,
        )
    except (subprocess.SubprocessError, OSError) as err:
        decky.logger.warning(f"curl download failed for LSFG-VK, trying Python fallback: {err}")
        _set(
            state="running", tag_name=tag,
            message=f"Downloading LSFG-VK {tag}...",
            install_as_latest=install_as_latest,
            stage="downloading-python-fallback",
            downloaded_bytes=0, total_bytes=asset_size,
            progress_fraction=0.0 if asset_size else None,
        )
        request = Request(download_url, headers={"User-Agent": "decky-proton-pulse"})
        with urlopen(request, timeout=180) as response, open(archive_path, "wb") as f:
            shutil.copyfileobj(response, f)
        dl_size = archive_path.stat().st_size
        frac = max(0.0, min(1.0, dl_size / asset_size)) if asset_size else None
        _set(
            state="running", tag_name=tag,
            message=f"Downloading LSFG-VK {tag}...",
            install_as_latest=install_as_latest,
            stage="downloading-python-fallback",
            downloaded_bytes=dl_size, total_bytes=asset_size, progress_fraction=frac,
        )


def _cancelled(tag: str, release: dict[str, Any]) -> dict[str, Any]:
    return {
        "success": False,
        "message": f"LSFG-VK install cancelled for {tag}.",
        "release": release,
    }
