name: Build Windows

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      workflow_name: Windows Build
      runs_on: windows-latest
      build_cmd: pnpm build
      enforce_diff_coverage: false
