name: Decky Latest (Debian)

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-decky-latest-reusable.yml
    with:
      workflow_name: Decky Latest (Debian)
      container_image: debian:12
      install_cmd: apt-get update && apt-get install -y bash ca-certificates curl git make rsync unzip xz-utils
