name: Build Bazzite

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      workflow_name: Bazzite Build
      container_image: fedora:41
      install_cmd: |
        dnf install -y bash ca-certificates curl git make rsync unzip xz
