name: Decky Latest (Ubuntu)

on:
  schedule:
    # Daily at 08:00 UTC
    - cron: "0 8 * * *"
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-decky-latest-reusable.yml
    with:
      workflow_name: Decky Latest (Ubuntu)
